// eslint.config.js
// Cấu hình ESLint chuẩn hóa theo Ticket K6: no-undef, no-redeclare, no-unreachable

module.exports = [
  {
    ignores: [
      'assets/vendor/**',
      'assets/js/vendor/**',
      'node_modules/**',
      'storage/**',
      '.git/**',
      'dashboard/**',
      '.ua/**',
      'archive/**',
      '**/*.min.js'
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // Trình duyệt tiêu chuẩn
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        EventSource: 'readonly',
        WebSocket: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        HTMLElement: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        AudioContext: 'readonly',
        webkitAudioContext: 'readonly',
        AbortController: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        Uint8Array: 'readonly',
        ArrayBuffer: 'readonly',
        DataView: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Worker: 'readonly',
        MediaRecorder: 'readonly',
        MediaStream: 'readonly',
        AudioWorkletNode: 'readonly',
        Notification: 'readonly',
        CSS: 'readonly',

        // Node.js / Tooling globals
        global: 'readonly',
        globalThis: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',

        // SheetApp2 Domain globals
        EventBus: 'writable',
        ApiService: 'writable',
        OSMDRenderer: 'writable',
        ChordDictionaryCore: 'writable',
        TapTempoCore: 'writable',
        MidiEngineCore: 'writable',
        AudioUnlockerCore: 'writable',
        SongLoaderCore: 'writable',
        AppModes: 'writable',
        FeatureFlags: 'writable',
        LiveSyncTransport: 'writable',
        LiveTransport: 'writable',
        SSETransport: 'writable',
        PollingTransport: 'writable',
        ModalEngine: 'writable',
        InEarAudioEngine: 'writable',
        StageInkEngine: 'writable',
        SongContext: 'writable',
        opensheetmusicdisplay: 'readonly',
        Tone: 'readonly',
        Tonal: 'readonly',
        App: 'writable',
        AppUI: 'writable',
        Store: 'writable',
        SheetAudioPlayer: 'writable',
        AutoScroller: 'writable',
        ChordCanvas: 'writable',
        InstrumentMixer: 'writable',
        AnnotationCanvas: 'writable',
        PageNav: 'writable',
        SongInfoBar: 'writable',
        PerformanceNotes: 'writable',
        HistoryManager: 'writable',
        SessionTracker: 'writable',
        DisplaySettings: 'writable',
        TransposeEngine: 'writable',
        URLState: 'writable',
        LiveSession: 'writable',
        SafeHtml: 'writable',
        ModalManager: 'writable',
        OfflineSetlistManager: 'writable',
        LiveSyncManager: 'writable',
        LearnApp: 'writable',
        LearnStore: 'writable',
        LearnSatb: 'writable',
        VoicingEngine: 'writable',
        MusicTransport: 'writable',
        ChordCard: 'writable',
        VirtualKeyboard: 'writable',
        LearnScore: 'writable',
        LearnControls: 'writable',
        LearnPractice: 'writable',
        LearnAccompaniment: 'writable',
        LearnAudio: 'writable',
        LearnMidi: 'writable',
        ChordTimelineNormalizer: 'writable',
        LEARN_EVENTS: 'writable',
        LEARN_FLAGS: 'writable',
        StageHud: 'writable',
        StageTimer: 'writable',
        StageAudio: 'writable',
        PedalMidiEngine: 'writable',
        StageRehearsal: 'writable',
        LiveBandApp: 'writable',
        LiveBandCatalog: 'writable',
        LiveBandConsole: 'writable',
        LiveBandHUD: 'writable',
        LiveBandCanvas: 'writable',
        ProjectorApp: 'writable',
        ProjectorSlides: 'writable',
        ProjectorHUD: 'writable',
        ProjectorStageCanvas: 'writable',
        ManagerApp: 'writable',
        ManagerRepertoire: 'writable',
        ManagerCommunity: 'writable',
        ManagerVersions: 'writable',
        ManagerCategories: 'writable',
        ManagerUsers: 'writable',
        ManagerUsage: 'writable',
        ManagerReviews: 'writable',
        ManagerNotifications: 'writable',
        EditorApp: 'writable',
        EditorExport: 'writable',
        EditorMidi: 'writable',
        EditorAudio: 'writable',
        EditorAi: 'writable',
        EditorParser: 'writable',
        EditorModifiers: 'writable',
        EditorHealth: 'writable',
        EditorDrag: 'writable',
        EditorUI: 'writable',
        EditorModal: 'writable',
        ChordProParser: 'writable',
        ChordProFormatter: 'writable',
        HelpModal: 'writable',
        TransposePickerModal: 'writable',
        TempoPickerModal: 'writable',
        ExportModal: 'writable',
        SettingsModal: 'writable',
        SyncStatusModal: 'writable',
        LibraryUI: 'writable',
        SetlistUI: 'writable',
        Metronome: 'writable',
        AudioPlayer: 'writable',
        AudioUnlocker: 'writable',
        ChordInputModal: 'writable',
        AnnotationTools: 'writable',
        BatchEditModal: 'writable',
        KeyboardHandler: 'writable',
        ServiceWorkerManager: 'writable',
        SongLoader: 'writable',
        StageLens: 'writable',
        GuitarLens: 'writable',
        BassLens: 'writable',
        DrumsLens: 'writable',
        VocalsLens: 'writable',
        MobileController: 'writable',
        Importer: 'writable',
        ToolbarController: 'writable',
        OsmdAudioPlayer: 'writable',
        ChordCanvasUI: 'writable',
        ChordCanvasXML: 'writable',
        PatternLibrary: 'writable',
        LearnSoundEngine: 'writable',
        PatternScheduler: 'writable',
        PatternGenerator: 'writable',
        PatternEngine: 'writable',
        LoopController: 'writable',
        PracticeTracker: 'writable',
        MelodyPracticeEngine: 'writable',
        MidiInputEngine: 'writable',
        ChordJudge: 'writable',
        LearnTransportBridge: 'writable',
        QRHelper: 'writable',
        MusicalPosition: 'writable'
      }
    },
    rules: {
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error'
    }
  }
];
